---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: demo
  namespace: monitoring
spec:
  version: v0.22.2
  replicas: 1
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: config-example
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi