---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-demo
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: smtp.gmail.com:587
      smtp_from: email@mail.com
      smtp_auth_username: email@mail.com
      smtp_auth_identity: email@mail.com
      smtp_auth_password: password
      smtp_require_tls: true
    route:
      group_by:
      - cluster
      - alertname
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: email
      routes:
      - receiver: email
        match:
          severity: warning
    receivers:
      - name: email
        email_configs:
        - to: email@mail.com
